### ISSUE TITLE
Make `robocorp-excel` stable

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#197]
Collect how far away are we from a stable version and release the first **v1** major version after all the required polishing.

### Blocked by
- [ ] Decision: Keeping the current API or inlining it symmetrically with what we have in `RPA.Excel.Files` (more [context](https://www.notion.so/robocorptechnologies/RPA-libraries-in-robocorp-d55ccdf0e3b6490b81c55b2086669e02) about porting-in RPA Framework libs to Robocorp)
- [x] https://github.com/robocorp/robocorp/issues/149

### Ideas and potential issues
- [ ] Mass reorganisation if required (structure & behaviour)
- [ ] Worksheet management
- [ ] Running macros (possibility to disable them)
- [ ] Pivot tables
- [ ] Prioritise and fix empty functions in `excel.worksheet`
- [ ] Fix code TODOs/FIXMEs
- [ ] Satisfactory testing coverage

### Notes
- Check this [excel-stable](https://github.com/robocorp/robocorp/compare/master...feat/excel-stable) branch before any change (in case we can learn from Ossi's past work)
